<?php

namespace AppBundle\Repository;

/**
 * castingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class castingRepository extends \Doctrine\ORM\EntityRepository
{
}
