<?php

namespace AppBundle\Repository;

/**
 * paysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paysRepository extends \Doctrine\ORM\EntityRepository
{
}
